id: P703E0A0A
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG14783
  title: སྔ་འགྱུར་རྒྱུད་འབུམ་ཕྱོགས་བསྒྲིགས།
  volumes:
    73ce70ffba9248b2895121fe5f730750:
      image_group_id: I1KG21606
      title: ''
      base_file: v001.txt
    201633fb3cb6416d8f20ec9bde8a225e:
      image_group_id: I1KG21607
      title: ''
      base_file: v002.txt
    3ec2f8e5b4644a448b57ef929fe8f926:
      image_group_id: I1KG21608
      title: ''
      base_file: v003.txt
    3d04393e2a40419fbad7f0e2d73ad74a:
      image_group_id: I1KG21609
      title: ''
      base_file: v004.txt
    ea63cb4a9fbc4f4eb2cfa41260e721e7:
      image_group_id: I1KG21610
      title: ''
      base_file: v005.txt
    9a162ede72b442cbb93748f444e3a774:
      image_group_id: I1KG21611
      title: ''
      base_file: v006.txt
    cbb5c44cc711479791c4cfbfa27807d8:
      image_group_id: I1KG21612
      title: ''
      base_file: v007.txt
    0bc6fced11e44c20bd784d76c825d2f8:
      image_group_id: I1KG21613
      title: ''
      base_file: v008.txt
    5a026cb0e6704e59843027114c7ed871:
      image_group_id: I1KG21614
      title: ''
      base_file: v009.txt
    36f34e4deee3463688c4ec1f2beb468c:
      image_group_id: I1KG21615
      title: ''
      base_file: v010.txt
    d3ff4ee46a8a411e814ac790551e1b8b:
      image_group_id: I1KG21616
      title: ''
      base_file: v011.txt
    c2a5f025490a4cf8982d569084d6813d:
      image_group_id: I1KG21617
      title: ''
      base_file: v012.txt
    ee60c069630143fbbb41bbd08046dce2:
      image_group_id: I1KG21618
      title: ''
      base_file: v013.txt
    6d48bd8d91354ff5ab800f658e5680d9:
      image_group_id: I1KG21619
      title: ''
      base_file: v014.txt
    17c27c8d2bcf4c5fbac75bc1cf0e89b4:
      image_group_id: I1KG21620
      title: ''
      base_file: v015.txt
    df2d2aaecc4e4f8aad6b517f896a86a6:
      image_group_id: I1KG21621
      title: ''
      base_file: v016.txt
    ed7e9d89aa284c4980f6a656d32cd0ce:
      image_group_id: I1KG21622
      title: ''
      base_file: v017.txt
    c868830a136d4a8d9229530b733a7a79:
      image_group_id: I1KG21623
      title: ''
      base_file: v018.txt
    21c3ff1b2daa4b4da8fef03e0009c523:
      image_group_id: I1KG21624
      title: ''
      base_file: v019.txt
    de2afb286cd948fdb0b33d2d9555eeb3:
      image_group_id: I1KG21625
      title: ''
      base_file: v020.txt
    dfce1076eaf34c71a5c2a4b0d2aeaf7d:
      image_group_id: I1KG21626
      title: ''
      base_file: v021.txt
    eac295aecc2340f4bb9c367e213311cd:
      image_group_id: I1KG21627
      title: ''
      base_file: v022.txt
    aa46fcba91d64fd88b5cf5b72b557876:
      image_group_id: I1KG21628
      title: ''
      base_file: v023.txt
    a082b3907f0c4c10aeba50d25d5866bf:
      image_group_id: I1KG21629
      title: ''
      base_file: v024.txt
    f01c8a37acda4b149f8f83bb2681600f:
      image_group_id: I1KG21630
      title: ''
      base_file: v025.txt
    893a3551b5124fcab9b5b97da1bcadcd:
      image_group_id: I1KG21631
      title: ''
      base_file: v026.txt
    bde03ffc37f64ba0945f061dfa163be8:
      image_group_id: I1KG21632
      title: ''
      base_file: v027.txt
    4d99e7256a6c4925b007e62a8ef00f5c:
      image_group_id: I1KG21633
      title: ''
      base_file: v028.txt
    9b7af4450a674c7682d77ecc442d60c3:
      image_group_id: I1KG21634
      title: ''
      base_file: v029.txt
    d72bc23207ba43d0899fa23831c28f64:
      image_group_id: I1KG21635
      title: ''
      base_file: v030.txt
    ed6d3fe1219b435399ff8aaa18752dec:
      image_group_id: I1KG21636
      title: ''
      base_file: v031.txt
    47cb10cd5bc148f9ac58a84c2f8a3590:
      image_group_id: I1KG21637
      title: ''
      base_file: v032.txt
    e58f7cc302f14867867fc64e33fe359f:
      image_group_id: I1KG21638
      title: ''
      base_file: v033.txt
    0641c043d3fe4f0b9f02b5e4d01a8762:
      image_group_id: I1KG21639
      title: ''
      base_file: v034.txt
    503c6ab3615e45cbb8fcb33a5d4e1b4c:
      image_group_id: I1KG21640
      title: ''
      base_file: v035.txt
    125cb29b05eb43bb8ea7ab2cbf8ab2c8:
      image_group_id: I1KG21641
      title: ''
      base_file: v036.txt
    f7db6ee5ec2343219324317787d3589f:
      image_group_id: I1KG21642
      title: ''
      base_file: v037.txt
    b3e79e37e1714a4ab6a375b07ca1512d:
      image_group_id: I1KG21643
      title: ''
      base_file: v038.txt
    2f446fcee88148a5babc4c9c0f7005ca:
      image_group_id: I1KG21644
      title: ''
      base_file: v039.txt
    c2c32273de474b49be88c66cca12f441:
      image_group_id: I1KG21645
      title: ''
      base_file: v040.txt
    80544ea0cdc44983ae2027b172d8c42b:
      image_group_id: I1KG21646
      title: ''
      base_file: v041.txt
    4128fff083884e92bf8d9a8029de89bb:
      image_group_id: I1KG21647
      title: ''
      base_file: v042.txt
    9afa81fc74424c82b731dcc90e8c07da:
      image_group_id: I1KG21648
      title: ''
      base_file: v043.txt
    eb00a3afb3894fcc9890825070cc4ddd:
      image_group_id: I1KG21649
      title: ''
      base_file: v044.txt
    065eb2ca2d0d4f81b81f615d6b150d8b:
      image_group_id: I1KG21650
      title: ''
      base_file: v045.txt
    dce10ef2987f43e482ca9f2ddd47b08c:
      image_group_id: I1KG21651
      title: ''
      base_file: v046.txt
    68c62a79ad404708a741e5c1ccb53278:
      image_group_id: I1KG21652
      title: ''
      base_file: v047.txt
    eb229c70325d42e9bc64e3aebc4ad16c:
      image_group_id: I1KG21653
      title: ''
      base_file: v048.txt
    79e31c8ec0fa48748ab595740fb2f490:
      image_group_id: I1KG21654
      title: ''
      base_file: v049.txt
    72c64552f3ae4807beea7e77406b819e:
      image_group_id: I1KG21655
      title: ''
      base_file: v050.txt
    cdfd31ac858a4be48713d3e2de3912c4:
      image_group_id: I1KG21656
      title: ''
      base_file: v051.txt
    fa84561539e04f8a818431c012857552:
      image_group_id: I1KG21657
      title: ''
      base_file: v052.txt
    64d9ce49dcc04c458a43c63039e7f235:
      image_group_id: I1KG21658
      title: ''
      base_file: v053.txt
    2d1437f943c0499c89d6ba94bd556da1:
      image_group_id: I1KG21659
      title: ''
      base_file: v054.txt
    39ad910f91df45b8a05d4458eecdd84f:
      image_group_id: I1KG21660
      title: ''
      base_file: v055.txt
    3ce339b3155a492eb2f32e4b52111a5e:
      image_group_id: I1KG21661
      title: ''
      base_file: v056.txt
    78adc107fd384cf6a977c4d39523182e:
      image_group_id: I1KG21662
      title: ''
      base_file: v057.txt
    3a0bfdfb09fb428eb91744b2d43dd282:
      image_group_id: I1KG21663
      title: ''
      base_file: v058.txt
    90a98aee9e6c4436afbf9ed8416e9b34:
      image_group_id: I1KG21664
      title: ''
      base_file: v059.txt
  author: ''
